[programs.localnet]
solana_ads = "GMyP4dhUir2sc41zTGRavav79nfim1WaTp2FUmiThHU2"

[registry]
url = "https://publana.vercel.app/"

[provider]
cluster = "localnet"
wallet = "/Users/shanginn/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
